export const LOGIN = '/login'
export const SIGNUP = '/signup'
export const DASHBOARD = '/dashboard'
export const DASHBOARD_STUDENT = '/dashboard/student'
export const DASHBOARD_TEACHER = '/dashboard/teacher'
